[0m14:21:24.840860 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105280b90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1053f2270>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1053f1c70>]}


============================== 14:21:24.843090 | 472de3a9-4551-4aef-8343-87a6d9b7ed20 ==============================
[0m14:21:24.843090 [info ] [MainThread]: Running with dbt=1.9.4
[0m14:21:24.843378 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/manhvd/.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt init my_dbt_postgre', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:21:24.852380 [debug] [MainThread]: Starter project path: /opt/anaconda3/lib/python3.12/site-packages/dbt/include/starter_project
[0m14:21:24.856187 [info ] [MainThread]: 
Your new dbt project "my_dbt_postgre" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m14:21:24.856381 [info ] [MainThread]: Setting up your profile.
[0m14:22:24.327917 [info ] [MainThread]: Profile my_dbt_postgre written to /Users/manhvd/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m14:22:24.334897 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 59.529274, "process_in_blocks": "0", "process_kernel_time": 0.135578, "process_mem_max_rss": "106987520", "process_out_blocks": "0", "process_user_time": 0.550532}
[0m14:22:24.336322 [debug] [MainThread]: Command `dbt init` succeeded at 14:22:24.336026 after 59.53 seconds
[0m14:22:24.337131 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105459550>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10539c4d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10551f8c0>]}
[0m14:22:24.337728 [debug] [MainThread]: Flushing usage events
[0m14:22:26.871504 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m14:50:29.484359 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106220950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106386780>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1063861b0>]}


============================== 14:50:29.486828 | 0a055080-84cb-47bc-81ab-ad78a868364d ==============================
[0m14:50:29.486828 [info ] [MainThread]: Running with dbt=1.9.4
[0m14:50:29.487294 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': '/Users/manhvd/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:50:29.487544 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/manhvd/Desktop/DE-Training/dbt-postgre/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:50:29.488758 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.036565583, "process_in_blocks": "0", "process_kernel_time": 0.118357, "process_mem_max_rss": "103727104", "process_out_blocks": "0", "process_user_time": 0.545704}
[0m14:50:29.489004 [debug] [MainThread]: Command `dbt run` failed at 14:50:29.488964 after 0.04 seconds
[0m14:50:29.489156 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106386420>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106387d70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1063865d0>]}
[0m14:50:29.489296 [debug] [MainThread]: Flushing usage events
[0m14:50:31.692107 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:23:51.086531 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110a676e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1110863f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111086000>]}


============================== 15:23:51.089005 | 5eca85b7-fd45-41c9-82c4-ccb98e0a1155 ==============================
[0m15:23:51.089005 [info ] [MainThread]: Running with dbt=1.9.4
[0m15:23:51.089308 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/manhvd/.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt deps', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m15:23:51.089690 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/manhvd/Desktop/DE-Training/dbt/dbt-postgre/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:23:51.090931 [debug] [MainThread]: Resource report: {"command_name": "deps", "command_success": false, "command_wall_clock_time": 0.038894083, "process_in_blocks": "0", "process_kernel_time": 0.115656, "process_mem_max_rss": "102154240", "process_out_blocks": "0", "process_user_time": 0.53222}
[0m15:23:51.091236 [debug] [MainThread]: Command `dbt deps` failed at 15:23:51.091190 after 0.04 seconds
[0m15:23:51.091402 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110c36a20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110f21a00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111086540>]}
[0m15:23:51.091554 [debug] [MainThread]: Flushing usage events
[0m15:23:52.920362 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m17:18:20.386571 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1070361b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x118e948f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x119186120>]}


============================== 17:18:20.389159 | 41268765-31a5-4480-9f7a-051ebcec240a ==============================
[0m17:18:20.389159 [info ] [MainThread]: Running with dbt=1.9.4
[0m17:18:20.389448 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/Users/manhvd/.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt docs serve', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m17:18:20.389709 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/manhvd/Desktop/DE-Training/dbt/dbt-postgre/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:18:20.390892 [debug] [MainThread]: Resource report: {"command_name": "serve", "command_success": false, "command_wall_clock_time": 0.039733708, "process_in_blocks": "0", "process_kernel_time": 0.11933, "process_mem_max_rss": "102825984", "process_out_blocks": "0", "process_user_time": 0.543495}
[0m17:18:20.391174 [debug] [MainThread]: Command `dbt docs serve` failed at 17:18:20.391136 after 0.04 seconds
[0m17:18:20.391339 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107106540>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1191392e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x118e94ef0>]}
[0m17:18:20.391479 [debug] [MainThread]: Flushing usage events
[0m17:18:22.598365 [debug] [MainThread]: An error was encountered while trying to flush usage events
